### ISSUE TITLE
关于A1112这道题

### ISSUE THREAD

**Issue by donaghyXu** [liuchuo/PAT#10]
为了评论一下我还特地注册了一下GitHub，感觉还蛮有用的（哈哈）。
for(int i = 0; i < s.length(); i++) {
        if(s[i] == pre)
            cnt++;
        else
            cnt = 1;
        m[s[i]] = (cnt % k == 0);
        pre = s[i];
    }
本来我是没什么思路，来寻找思路，然后找到了这位妹纸^_^，这一段这里我发觉有点问题，你的这个是只要后面有不是连续的3个，就给m[s[i]]赋值false，拿样例打比方，如果前面都是1个2个s，最后一个单词出现了连续的三个s，按照你的思路，这个s就会被认为是坏的键，从而输出了。

**Comment by liuchuo** [comment]
其实这个问题早就发现了。。然后我改了博客上的代码没有改这里的。。谢谢提醒，我再改一下。。～
