### ISSUE TITLE
学姐求指教啊啊啊啊啊啊啊啊

### ISSUE THREAD

**Issue by zou-sq** [liuchuo/PAT#23]
弱鸡来问下B1067那道题，为啥总是拿不到满分，学姐能指教下吗，我的qq2567432944，没拿满分有点别扭感觉

**Comment by liuchuo** [comment]
可是……我能拿满分，这并不是我知道你写的代码为什么不满分的理由啊…… // 我拒绝被当编译器

**Comment by liuchuo** [comment]
qq已加，交个朋友可以，别发代码让我调试就行……(*^__^*)
