### ISSUE TITLE
PAT A1025这道题，学姐用的vector我用的数组怎么有两个测试点过不去 求助！！！

### ISSUE THREAD

**Issue by SYaoJun** [liuchuo/PAT#24]
``#include <cstdio>
#include <algorithm>
#include <cstring>
using namespace std;
const int maxn = 305;
const int N =30010;
struct Node{
	char name[15];
	int score,local,rankl,rankt;
}E[N];

bool cmp(Node a,Node b){
	if(a.score != b.score)
		return a.score >b.score;
	else return strcmp(a.name,b.name)<0;
}
int main(){
	int n,k,num=0;
	char id[15];
	scanf("%d",&n);
	for(int i=1;i <= n;i++){
		scanf("%d",&k);
		Node stu[maxn]={0};
		int j;
		for(j=0;j<k;j++){
			scanf("%s%d",stu[j].name,&stu[j].score);
		}
			sort(stu,stu+j,cmp);
			strcpy(E[num].name ,stu[0].name);
			E[num].score = stu[0].score;
			E[num].local = i;		
			E[num++].rankl = 1;			
		for(int v=1;v < j;v++){
			if(stu[v-1].score==stu[v].score){
				stu[v].rankl =stu[v-1].rankl;
			}else{
				stu[v].rankl= v+1;
			}
			strcpy(E[num].name ,stu[v].name);
			E[num].score = stu[v].score;
			E[num].local = i;
			E[num].rankl = stu[v].rankl;
			num++;
		}
	}
	sort(E,E+num,cmp);
	E[0].rankt = 1;
	for(int v=1;v < num;v++){
		if(E[v-1].score==E[v].score){
			E[v].rankt = E[v-1].rankt;
		}else{
			E[v].rankt= v+1;
			}
	}
	printf("%d\n",num);
	for(int v=0;v < num;v++){
		printf("%s %d %d %d\n",E[v].name,E[v].rankt,E[v].local,E[v].rankl);		
	}
	return 0;
}

**Comment by liuchuo** [comment]
抱歉才看到，问题解决了吗？为什么经常有人问我为什么测试点不通过。。。我为此写了篇文章希望对你有帮助～「为什么我的这段代码有几个测试点不通过呢」系列及常见问题FAQ 
 https://www.liuchuo.net/archives/4381
