### ISSUE TITLE
[PAT-A-1028] 一个bug？

### ISSUE THREAD

**Issue by littlesevenmo** [liuchuo/PAT#33]
您好，在您的博客[1028题解](https://www.liuchuo.net/archives/2120)中
我认为有个bug。
题目要求在名字和成绩相同的时候，按学号从小到大排序。
![tim 20180411234509](https://user-images.githubusercontent.com/7915267/38627794-63a7829a-3de2-11e8-9754-2cb557b04238.jpg)

但是您的代码中cmp1函数并没有反映出来。
以以下测试为例：
6 2
000007 James 87
000001 James 81
000002 James 82
000003 James 83
000004 James 84
000005 James 85
用您的代码输出结果如图：
![tim 20180411234332](https://user-images.githubusercontent.com/7915267/38627724-3691d9c2-3de2-11e8-9e2d-e7089aa63f95.jpg)

**Comment by liuchuo** [comment]
确实考虑不周了，已改，谢谢提醒～
