### ISSUE TITLE
PAT-A-1096更高效的解法

### ISSUE THREAD

**Issue by littlesevenmo** [liuchuo/PAT#51]
不用算连续因子最多不会超过12个。也不需要三重循环，两重循环即可。

直接去计算当前部分乘积能不能整除N。

代码如下：
```cpp
#include<iostream>
#include<cmath>
using namespace std;
long int num,temp;
int main(){
	cin >> num;
	int first = 0, len = 0, maxn = sqrt(num);
	for (int i = 2; i <= maxn; i++){
		int j; temp = 1;
		for ( j = i; j <= maxn; j++){
			temp *= j;
			if (num%temp != 0)break;
		}
		if (j - i > len){
			len = j - i;
			first = i;
		}
	}
	if (first == 0)cout << 1 << endl << num;
	else {
		cout << len << endl;
		for (int i = 0; i < len; i++){
			cout << first + i;
			if (i != len - 1)
				cout << '*';
		}
	}
	return 0;
}
```

**Comment by liuchuo** [comment]
您好，感谢提供的更优解，已将你的代码作为Update v2.0更新在了liuchuo.net、CSDN博客的PAT甲级1096题、GPLT的L1-006题的题解中并署名。提一点小建议：1 分析可以写的更详细，因为如果代码无问题，你写的分析我会直接复制在博客的题解中，不仅是为了我能够理解，还要为了方便看博客的人理解，所以可以写的更加详细，谢谢～2 分析不要总是那么多独立的句子和句号（句号之间至少应该是一个完整的语句吧），因为会显得很不温柔（很凶）的样子～ 3 记得代码一定要return 0;哦～
PS：你的代码风格很好 本仓库愿意长期接受你提供的更高效的代码
如有需要我会在仓库的readme.md文件中末尾加上这句话：感谢@littlesevenmo为PAT甲级多次提供的更效的解法
