### ISSUE TITLE
学姐麻烦把各级文件夹名还是命名成英文吧，终端下打字真的苦逼呀

### ISSUE THREAD

**Issue by 4thirteen2one** [liuchuo/PAT#54]
1. “PAT”其实不用写，毕竟大家都是“PAT“（滑稽
2. 中文括号和英文括号混输，表示很伤
3. 直接用BasicLevel、AdvancedLevel和TopLevel吧，后面的Java可以加下划线添上

After all，幸苦你啦

**Comment by liuchuo** [comment]
我也是用终端的呀，我没有遇到困扰呀，首先文件夹前缀都是英文的，为什么不使用终端的tab自动补全呢？

**Comment by liuchuo** [comment]
对于中文早些年还有这样的困扰，现在已经不存在的啦，况且乙级里面的题目文件名也是中文的呀

**Comment by fs19910227** [comment]
我用git poll 的时候就有这个麻烦啦 。
中文自然是支持的。只不过终端虽然可以自动补全，但还是要打一个字的，因为前缀都一样。切输入法就比较麻烦了。
java那个文件夹括号是中文全角的这个（，而不是这个(

**Comment by 4thirteen2one** [comment]
因为我是安卓手机SSH连到树莓派上做的……安卓上的Termux和JuiceSSH下输入中文都得划一下键盘拓展栏，enter选中后字却也同时输进去了。然后文件夹里带空格得转义，也麻烦，还是用下划线代替吧 @liuchuo

**Comment by liuchuo** [comment]
@fs19910227 我一直用的iterm + oh my zsh，我所说的前缀一样，是指我输入PAT按tab键就会自动让我选择所有包含前缀“PAT”的文件夹名称（按tab选），所以从来没有遇到过这样的困扰，切输入法比较麻烦也不太明白是什么意思。。我在终端里面直接输入法按一下Shift就变英文了。。或者直接中文输入回车就变英文了。。是不是你们输入法或者终端没装方便的插件全用的原生的呀。。。而且即使文件夹改了，里面的文件名有很多都是包含中文字的，这个怎么解决呢？

**Comment by liuchuo** [comment]
你们终端用的这么憋屈的嘛。。竟然有这么多困扰。。震惊了。。。

**Comment by liuchuo** [comment]
文件夹名字都改掉了，心痛啊，我之前做的所有辛苦写的commit的信息都被最新的移动文件夹覆盖了，之前还想通过commit信息一眼看出哪些题目更新过更优解法呢。。。

**Comment by liuchuo** [comment]
不过本着开源代码的精神还是接受了你们的建议QAQ，内心是十分委屈的！！！

**Comment by 4thirteen2one** [comment]
tab有用的，不过如果大家都是以“PAT”开头就区分不开了（毕竟大家都是PAT\扶额……所以可以省去，直接以各自真实分类命名文件夹，从首字母就可以直接达到目的文件夹（A or B  or C），

然后再tab，补全到底是Java子分类还是C++的信息，这样整个文件夹命名就完整区分了，一目了然

**Comment by 4thirteen2one** [comment]
看到了改动！感谢学姐接受建议，么么哒！

**Comment by 4thirteen2one** [comment]
呃呃……commit的信息如果因为这次变更文件夹名而变得不那么容易看到，我表示抱歉哈，没考虑到那上面去……

不过！以后的更新，信息变更应该会变得更直观！这次应该算是一劳永逸吧\认真点头

辛苦啦

**Comment by liuchuo** [comment]
唉，我是出于这样的考虑：1 很多刷题的逛github的都是因为我的原因才来了解github的，看到github上全英文已经够头疼了，点进来还要看英文是很不好的体验的，这个在我高三结束刚接触github时候深有体会。。。2 因为pat这个缩写不仅仅是代表PAT程序设计能力考试，你搜github上pat就会发现有很多其它类型的仓库了，写PAT甲级、乙级也是为了让人一目了然觉得找对了仓库而已。。。。3 最最重要的就是会把我辛苦弄的commit信息都抹掉，刚刚我一改变文件夹，有630多个文件进行了改动，所有的commit message都要改成统一的，我写什么commit都不对，我写“rename”吧所有的文件都会变成commit信息为rename很很影响美观。。。很多题目已经完全定型了之后不会有什么改变，就会rename的commit一直留着，如果commit只会改变文件夹的我就不会这么不愿意改了 4 最最最最最重要的是我身边很多人帮我维护代码时候都没有遇到这样的困扰。。。。。。。以上

**Comment by liuchuo** [comment]
<img width="648" alt="qq20180716-224420 2x" src="https://user-images.githubusercontent.com/11920560/42765854-89b1980e-894b-11e8-9dec-dfb627017026.png">

**Comment by 4thirteen2one** [comment]
![screenshot_2018-07-16 issue 54 liuchuo pat](https://user-images.githubusercontent.com/14036563/42765051-b5a2d722-8949-11e8-9582-61e092c3fb77.png)

1. 其实仓库简介有很写明显是浙大PAT题解的，关于PAT关键字的仓库在GitHub上有挺多容易让人不好找这一点大可不用担心（我当时搜PAT得到的第一个结果可就是这个呢

2. 英文不好的话，我觉得这不是借口，毕竟Github是国外网站了，编程都学的了这点专业英语应该能应付得了的吧，你也不要太心软惯着大家了

3. commit信息之类的，如果积累太多一下子改动了确实挺头疼的……但为了统一性这也是没办法……辛苦你们了。我才刚开始刷题，以后如果可以我也会帮着贡献仓库建设的。

One more thing，我看了一下源码里面你们很贴心地在开头加上了题目描述，但不是以注释形式附上的，这样就造成了文件不可直接拿来编译。不过这一点到底改不改都行：改了固然是更方便可以拿来直接编译运行，但同时也“太方便了”，拿来主义不好，还是得自己动手；不改的话也行，可以考虑把所有文件以markdown的形式改写，题目描述用`#`、`>`等标签，代码用

```
#include <stdio.h>
int main() {
    printf("Hello world!\n");
    return 0;
}
```
的形式。
不过这样就真的大规模改动了……哈哈哈，你考虑一下，改不改都行。

**Comment by liuchuo** [comment]
1. 搜pat结果第一个就是是因为我好不容易爬到了第一个，用了两三年的时间。。。。。。。排名按照star和fork的数量决定的
2. 不过想想也对，估计英语不好的就止步于看博客就够了，也不指望ta能够给我pull request和写issue了
3. 你刷题的话还是建议直接看博客，github上代码有些题目有时候并不是最新的稳定版，稳定版在liuchuo.net上面，有更优代码再到github上来给我发pr
4. 不是所有人都能直接打开md文档的，github上的md文件也是为了直接在主页readme中能够看见，具体解决方法参见3，博客上所有文章使用html + code插件，所有代码都在code框里面可以直接复制
5. 所有的困扰都来自于这根本不是个开源项目，只是题解而已，没必要纠结那么多了，如果是工程项目里面肯定没有这些问题

**Comment by 4thirteen2one** [comment]
好的！

**Comment by yanyingwang** [comment]
弱弱的说，你们其实可以尝试一下软链接
