### ISSUE TITLE
PAT乙级 1005 继续(3n+1)猜想： 下面这样优化下会不会好些

### ISSUE THREAD

**Issue by xyz8772232** [liuchuo/PAT#55]
![image](https://user-images.githubusercontent.com/7192860/42755639-9e260326-892b-11e8-97cf-fc0a5fd1f56d.png)

**Comment by xyz8772232** [comment]
https://github.com/equinusocio/material-theme

好像是这个，很久以前弄得，记不太清了
![image](https://user-images.githubusercontent.com/7192860/42800281-be973132-89cd-11e8-9a88-a8e50bfa1dde.png)

**Comment by liuchuo** [comment]
好的，谢谢你～
