### ISSUE TITLE
1008. 数组元素循环右移问题 (20)-PAT乙级真题

### ISSUE THREAD

**Issue by xyz8772232** [liuchuo/PAT#57]
reverse运用的很巧妙！！！

原解m的判断略复杂，直接对n取模比较好理解
![image](https://user-images.githubusercontent.com/7192860/42857929-9f839b08-8a7e-11e8-8f6d-ebe0973aaacf.png)

**Comment by liuchuo** [comment]
好的，已改，谢谢谢
