### ISSUE TITLE
PAT-A-1103 优化代码，大幅缩短耗时

### ISSUE THREAD

**Issue by littlesevenmo** [liuchuo/PAT#58]
这道题考的是DFS+剪枝。
我认为主要剪枝的地方有三个：
1，tempK==K但是tempSum!=n的时候需要剪枝。
2，在枚举的时候，按顺序枚举，上界或者下界可进行剪枝。
3，当且仅当tempSum + v[index] <= n时，进行下一层的DFS，而不要进入下一层DFS发现不满足条件再返回。这样开销会比较大。

修改后的代码如下：
```cpp
#include <iostream>
#include <vector>
#include <cmath>
using namespace std;
int n, k, p, maxFacSum = -1;
vector<int> v, ans, tempAns;
void init() {
	int temp = 0, index = 1;
	while (temp <= n) {
		v.push_back(temp);
		temp = pow(index, p);
		index++;
	}
}
void dfs(int index, int tempSum, int tempK, int facSum) {
	if (tempK == k ) {
		if (tempSum == n) {
			if (facSum > maxFacSum) {
				ans = tempAns;
				maxFacSum = facSum;
			}
		}
		return;
	}
	while(index >= 1) {
		if (tempSum + v[index] <= n) {
			tempAns[tempK] = index;
			dfs(index, tempSum + v[index], tempK + 1, facSum + index);
		}if (index == 1)
			return;
		index--;
	}
}
int main() {
	scanf("%d%d%d", &n, &k, &p);
	init(); tempAns.resize(k);
	dfs(v.size() - 1, 0, 0, 0);
	if (maxFacSum == -1) {
		printf("Impossible");
		return 0;
	}
	printf("%d = ", n);
	for (int i = 0; i < ans.size(); i++) {
		if (i != 0) printf(" + ");
		printf("%d^%d", ans[i], p);
	}
	return 0;
}
```
耗时大概在350~400ms之间，如图。
![tim 20180719172310](https://user-images.githubusercontent.com/7915267/42934277-5788d7c2-8b79-11e8-8b38-6186c8c3956f.jpg)

但是，经测，您的代码耗时约在900~1000ms之间。

**Comment by liuchuo** [comment]
博客、csdn和github已修改并署名
然而这道题的 [时间限制: 1200ms] 明显和别的题目时间限制400ms有很大差别，在考试环境下还是会按照我原来那样基础的DFS即可～降低了复杂度却增加了一次性理解的难度，会被初学者认为是“不知如何想到的、后期加工的、没有必要的代码”
若想试试优化时间复杂度，可以尝试LeetCode OJ，在那里基本是时间复杂度越低越好
在PAT考试的情况下，我认为还是“最先能想到的”、“最先能解决这道问题”、“最容易理解的”方式更新代码更加合适

**Comment by liuchuo** [comment]
```
if (tempSum + v[index] <= n) {
			tempAns[tempK] = index;
			dfs(index, tempSum + v[index], tempK + 1, facSum + index);
		}if (index == 1)
			return;
```
希望下次不要出现这样奇怪格式的代码……if为什么要放在上一个大括号后面

**Comment by liuchuo** [comment]
```
if (tempK == k ) {
```
k后面多了个空格
```
init(); tempAns.resize(k);
```
没有什么关联的两句话一般不放同一行，除非是if语句后的单句语句（Google代码风格标准）
```
if (tempSum == n) {
			if (facSum > maxFacSum) {
				ans = tempAns;
				maxFacSum = facSum;
			}
		}
```
这种形式正常人会写成if(xxx && xxx)的形式而不是两个if语句

刚刚提交了才发现这些小细节，又重新去改了一遍
有时候遇到思路不错的代码只能自己手动慢慢帮改格式，心累……

**Comment by littlesevenmo** [comment]
感谢指正，我现在用的IDE是VS2015，为了方便，我都是一路tab下来的，所以目前根本没有考虑什么代码风格的事。
我以后会注意的，向你学习。同时我现在就去看Google代码风格标准。
再次感谢。

**Comment by liuchuo** [comment]
其实在我见过的大多数代码里面你的代码格式已经是相当可以的了……有的简直不忍直视……
我是直接sublime代码的，格式都是自己手敲的，习惯成自然，脱离IDE后代码也很少会有bug，hhhhha

**Comment by littlesevenmo** [comment]
谢谢....其实每次给你提交之前，我都是检查检查再检查的。
我平时自己写都是直接按TAB，管他啥风格，自己能看懂，能最快时间AC对我来说才是最重要的（至少现在是）。也有可能是因为我太懒了吧...._(:з」∠)_
