### ISSUE TITLE
最萌程序媛就是你了！

### ISSUE THREAD

**Issue by kellenf** [liuchuo/PAT#59]
很早的时候就看到你的博客了，当时我准备考PAT，看了一些你的题解，但是那个寒假也没刷多少题，结果考了20多分，实在是惭愧啊。
不过也没事，我后来也没考浙大，PAT分数也不要紧，反正结果能顺利读研就行了，这次又翻了翻你的博客，也翻了翻你的github，不得不说你真的是一位非常非常优秀的程序媛！！!
你现在应该也毕业了吧，能不能透露下去向，求认识。

**Comment by liuchuo** [comment]
现在是无业游民、社会闲散人员～暂时也不想就业～gap year进行中……
认识的话，我们不是已经认识了么～有缘会在现实中相会的～

**Comment by yanyingwang** [comment]
大叔不小心路过，特地前来留言，原来

github年轻人都是在这么玩的！

**Comment by thedogb** [comment]
见识了，果然是社交网络

**Comment by liuchuo** [comment]
因为关于代码问题的issue都被解决了就被close了呀～hhhhhhha（捂脸逃

**Comment by liuchuo** [comment]
dev里添加c++11标准即可，vs没用过

**Comment by sontallive** [comment]
最萌有什么用，我是你永远都得不到的人！

**Comment by liuchuo** [comment]
(⊙o⊙)你成功引起了我的主意

**Comment by sontallive** [comment]
那又怎么样，我不会加你美丽的微信的！

**Comment by CaiNiaoHui** [comment]
学姐好活跃啊，学姐是浙大的吗 @liuchuo
