### ISSUE TITLE
关于甲级1003题有点小困惑

### ISSUE THREAD

**Issue by qtg2015sclt** [liuchuo/PAT#6]
这句：
```c
if(w[u] + weight[v] > w[v])
    w[v] = w[u] + weight[v];
```
对w[v]的更新是不是太过简单了，如果在这个测试点下：
5 6 0 4
1 2 10 5 3
0 1 2
0 2 3
0 4 6
1 3 2
2 4 3
3 4 2
正确答案是3 21（应该是吧……），但代码给出的结果是3 14。
如果我哪里理解的有问题，请指教QAQ
从你的博客中得到了很大的帮助，也在这里表达一下感谢~

**Comment by liuchuo** [comment]
你好，我尝试理解了下你的测试用例，答案应该就是3 14呀，
For each test case, print in one line two numbers: the number of different shortest paths between C1 and C2, and the maximum amount of rescue teams you can possibly gather.要输出的是：路线的条数，以及这些条数里面最大可以召集的队伍，并不是所有的路线都加起来的队伍的总个数呀，就是1+10+3=14呀，your job is to lead your men to the place as quickly as possible, and at the mean time, call up as many hands on the way as possible.选择的是最快的路，如果与此同时能够叫上更多的队伍更好，所以最后还是选一条路呀

**Comment by liuchuo** [comment]
另外，谢谢关注～

**Comment by qtg2015sclt** [comment]
原来是我自己没读懂题目，真是太麻烦你啦，谢谢你这么耐心给我解释⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by liuchuo** [comment]
冥冥之中感觉你很萌

**Comment by qtg2015sclt** [comment]
是因为你特别萌OwO
