### ISSUE TITLE
Advanced Level的 Tree Traversals Again 这题代码运行不了耶

### ISSUE THREAD

**Issue by 1160208849wfl** [liuchuo/PAT#62]

**Comment by liuchuo** [comment]
我试了一下，可以运行，也可以通过PAT的OJ，提交结果是答案正确

**Comment by 1160208849wfl** [comment]
可以运行，是我太逗比了；没敲EOF。😂😂😂

**Comment by liuchuo** [comment]
EOF是什么，为什么要敲这个才能运行

**Comment by 1160208849wfl** [comment]
EOF([End Of File](https://baike.baidu.com/item/EOF)) 因为用了~scanf ,在windows 下EOF用ctrl+z+回车输入EOF,在mac下通过control + D来输入 :）

**Comment by 1160208849wfl** [comment]
可能学姐的mac跟windows的操作不同吧🙃

**Comment by liuchuo** [comment]
这意思啊，你说的是“运行不了”，我试了下用xcode可以编译运行跑起来
