### ISSUE TITLE
关于PAT-A-1048使用局部数组测试点二不通过的问题

### ISSUE THREAD

**Issue by renrugangbei** [liuchuo/PAT#63]
当使用全局数组时可以通过测试点二，如下图。
![2018-07-27 1](https://user-images.githubusercontent.com/18330560/43323606-b2cf0284-91e4-11e8-9915-2facc1ee27a8.png)
但是当使用局部数组并使用 fill() 置零后测试点二不通过，如下图
![2018-07-27](https://user-images.githubusercontent.com/18330560/43323784-277075a0-91e5-11e8-9cc1-7b15878d4bd7.png)
除了声明数组以外的代码都相同，代码如下，但是结果不一样....求解....
```
int main(){
	int cnum,mnum;
	scanf("%d %d",&cnum,&mnum);
	int table[1005];
	fill(table, table + 1005, 0);
	for(int i = 0; i < cnum; i++){
		int temp;
		scanf("%d",&temp);
		table[temp]++;
	}
	for(int i = 0; i < 1005; i++){
		if(table[i] && table[mnum - i]){
			if((i == mnum - i) && table[i] <= 1){
				continue;
			}else{
				printf("%d %d\n",i,mnum - i);
				return 0;
			}
		}
	}
	printf("No Solution");
}
```

**Comment by liuchuo** [comment]
神奇，怎么做到的

**Comment by renrugangbei** [comment]
我也不清楚.... 讲道理的话 局部数组fill()之后和全局数组没什么大区别啊...
