### ISSUE TITLE
PAT-A-1144 更高效的解法

### ISSUE THREAD

**Issue by littlesevenmo** [liuchuo/PAT#66]
思路分析：
1. 题目中说，给定一个正整数N和N个数，求这N个数中，最小的没有出现的正整数，为方便，记这个数为P。
2. 在这N个数是1\~N的情况下，P具有最大值，为N+1。因此我们只需要记录在[1\~N]这个范围内的数即可。
3. 相比于在map中从小到大一个个的查找，直接用数组更为方便。
代码如下：
```cpp
#include<iostream>
using namespace std;
int temp, N, cnt = 0;
bool num[100002] = { 0 };
int main(){
	cin >> N;
	for (int i = 0; i < N; i++) {
		scanf("%d", &temp);
		if (temp > N || temp <= 0)
			continue;
		num[temp] = true;
	}
	while (++cnt){
		if (num[cnt] == false)break;
	}
	cout << cnt;
	return 0;
}
```
只需要26ms。

**Comment by liuchuo** [comment]
一道20分的简单题为什么还要纠结更高效……用一个100000的大数组代替map真的是更优解么……那我改成unordered_map是不是又更高效了？。。。

**Comment by liuchuo** [comment]
我觉得能解决问题且用的方法不是特别暴力夸张的代码都是好代码，况且用map优化大数组才是竞赛里的常规思维，没有谁会觉得上来开个10万的大数组才是更合适的吧？
另：大数组在外面不用初始化。
又另：在c++里面bool赋值的时候最好是false和true而不是c里面惯用的0和1。
最后：我们有这时间在这里为了一道对考试对算法都毫无影响的题目纠结不如多学点知识多刷两道题多背点单词？
