### ISSUE TITLE
1081 Rational Sum PAT 测试更新了

### ISSUE THREAD

**Issue by Alexader** [liuchuo/PAT#68]
代码没有错，看到柳神博客里说“应该还要考虑整数和小数部分都为0时候输出0的情况，但是测试用例中不涉及，所以如果没有最后两句也是可以AC的”，来提醒一下大家，PAT测试更新了，需要考虑全零的情况。今天这个卡了好久，是我太蠢了呜呜呜TT

**Comment by liuchuo** [comment]
嗯嗯已改～果然当年的我是聪明机智的2333333

**Comment by liuchuo** [comment]
不蠢不蠢，抱抱～
