### ISSUE TITLE
[PAT_B_1030] dynamic allocated memory not freed

### ISSUE THREAD

**Issue by jJayyyyyyy** [liuchuo/PAT#7]
* [PAT_B_1030](https://github.com/liuchuo/PAT/blob/master/PAT%E4%B9%99%E7%BA%A7(Basic%20Level)/1030.%20%E5%AE%8C%E7%BE%8E%E6%95%B0%E5%88%97(25).cpp) --- L42

```cpp
long long int *a = new long long int [n];
```

Dynamic allocated array `a[]` has not been freed with `delete []`, which may not supposed to be a good habit:(

**Comment by liuchuo** [comment]
当时大一的时候写的不懂，后来都用vector了。

**Comment by liuchuo** [comment]
好的谢谢提醒～大一时候写的，当时习惯不好，后来都是用的vector～
