### ISSUE TITLE
pat甲级1111

### ISSUE THREAD

**Issue by wandada** [liuchuo/PAT#71]
这题的最短路径和最快路径的思路应该是完全一样的，dispre和timepre都可以用一维数组存，这样dfsTimepath就可以和dfsdispath一样简单了。这里主要是类似weight数组建立一个NodeNum[]数组来存到每个节点的节点数，概念类似weight.
另外这个
  **for(int i = 0; i < n; i++)
        dispre[i] = i;**
这段好像没有什么意义，删除之后也是可以的

在原答案的基础上加了一丢丢修改，如下：
#include <cstdio>
#include <algorithm>
#include <vector>
using namespace std;
const int inf = 999999999;
int dis[510], Time[510], e[510][510], w[510][510], dispre[510],Timepre[510], weight[510],NodeNum[510];
bool visit[510];
vector<int> dispath, Timepath, temppath ;
int st, fin, minnode = inf;
void dfsdispath(int v) {
    dispath.push_back(v);
    if(v == st) return ;
    dfsdispath(dispre[v]);
}

**void dfsTimepath(int v) {
   Timepath.push_back(v);
    if(v == st) return ;
    dfsTimepath(Timepre[v]);
}**
int main() {
    fill(dis, dis + 510, inf);
    fill(Time, Time + 510, inf);
    fill(weight, weight + 510, inf);
    fill(e[0], e[0] + 510 * 510, inf);
    fill(w[0], w[0] + 510 * 510, inf);
    int n, m;
    scanf("%d %d", &n, &m);
    int a, b, flag, len, t;
    for(int i = 0; i < m; i++) {
        scanf("%d %d %d %d %d", &a, &b, &flag, &len, &t);
        e[a][b] = len;
        w[a][b] = t;
        if(flag != 1) {
            e[b][a] = len;
            w[b][a] = t;
        }
    }
    scanf("%d %d", &st, &fin);
    dis[st] = 0;
    **for(int i = 0; i < n; i++)
        dispre[i] = i;**
    for(int i = 0; i < n; i++) {
        int u = -1, minn = inf;
        for(int j = 0; j < n; j++) {
            if(visit[j] == false && dis[j] < minn) {
                u = j;
                minn = dis[j];
            }
        }
        if(u == -1) break;
        visit[u] = true;
        for(int v = 0; v < n; v++) {
            if(visit[v] == false && e[u][v] != inf) {
                if(e[u][v] + dis[u] < dis[v]) {
                    dis[v] = e[u][v] + dis[u];
                    dispre[v] = u;
                    weight[v] = weight[u] + w[u][v];
                } else if(e[u][v] + dis[u] == dis[v] && weight[v] > weight[u] + w[u][v]) {
                    weight[v] = weight[u] + w[u][v];
                    dispre[v] = u;
                }
            }
        }
    }
    dfsdispath(fin);
    Time[st] = 0;
    fill(visit, visit + 510, false);
    for(int i = 0; i < n; i++) {
        int u = -1, minn = inf;
        for(int j = 0; j < n; j++) {
            if(visit[j] == false && minn > Time[j]) {
                u = j;
                minn = Time[j];
            }
        }
        if(u == -1) break;
        visit[u] = true;
        for(int v = 0; v < n; v++) {
            if(visit[v] == false && w[u][v] != inf) {
                if(w[u][v] + Time[u] < Time[v]) {
                    Time[v] = w[u][v] + Time[u];
                    **Timepre[v]=(u);
                    NodeNum[v]=NodeNum[u]+1;**
                } else if(w[u][v] + Time[u] == Time[v]&&**NodeNum[u]+1<NodeNum[v])** {
                    **Timepre[v]=(u);**
                    **NodeNum[v]=NodeNum[u]+1;**
                }
            }
        }
    }
    dfsTimepath(fin);
    printf("Distance = %d", dis[fin]);
    if(dispath == Timepath) {
        printf("; Time = %d: ", Time[fin]);
    } else {
        printf(": ");
        for(int i = dispath.size() - 1; i >= 0; i--) {
            printf("%d", dispath[i]);
            if(i != 0) printf(" -> ");
        }
        printf("\nTime = %d: ", Time[fin]);
    }
    for(int i = Timepath.size() - 1; i >= 0; i--) {
        printf("%d", Timepath[i]);
        if(i != 0) printf(" -> ");
    }
    return 0;
}

**Comment by liuchuo** [comment]
万分感谢，但是……
由于你代码没有放在代码块里，里面的内容比如include后面的内容都显示不出来丢失了。。。
PS：如果可以的话帮我写一下详细分析，我好直接贴在博客上的分析位置。。不然我更新了代码不更新分析总不太好。。

**Comment by wandada** [comment]
分析：前提：因为题目中提出了不存在两条路线同时节点数一样且最短时间相同。如同不存在两条路线最短路径长度相同且花的时间也相同，否则第一个问题最短路径中的dispre就不可能是一维数组来存。。。
类比
第一条件最短路径， 第二条件时间最短
第一条件最短时间，第二条件为节点数最少。
这里可以一一对应，也就是把最短时间看成第一个问题里的最短路径，节点数看成时间最短(这样想：**第一条件里这个时候把边上的时间看成路径长度；第二条件中一个节点看成一单位时间，就完全转化为第一个问题了**)。。
类似第一问题，我们在第二问题的dijkstra算法中，就在两条同终点路线时加入判断，比较两条路线的节点数（NodeNum数组存储的是路径经过该点时已经经过的节点数）
` else if(w[u][v] + Time[u] == Time[v]&&**NodeNum[v]>NodeNum[u]+1**) {
Timepre[v]=(u);
NodeNum[v]=NodeNum[u]+1;
}`
类似第一问题中比较两条路线的已经花去的时间，
`else if(e[u][v] + dis[u] == dis[v] && **weight[v] > weight[u] + w[u][v]**) {
weight[v] = weight[u] + w[u][v];
dispre[v] = u;
}`
这根据前面的分析必然是惟一的。

ps:下面这段代码没有必要.hhhhh,因为没起任何作用。
`for(int i = 0; i < n; i++)
dispre[i] = i;`
代码如下：
`
#include <cstdio>
#include <algorithm>
#include <vector>
using namespace std;
const int inf = 999999999;
int dis[510], Time[510], e[510][510], w[510][510], dispre[510],Timepre[510], weight[510],NodeNum[510];
bool visit[510];
vector dispath, Timepath, temppath ;
int st, fin, minnode = inf;
void dfsdispath(int v) {
dispath.push_back(v);
if(v == st) return ;
dfsdispath(dispre[v]);
}
void dfsTimepath(int v) {
Timepath.push_back(v);
if(v == st) return ;
dfsTimepath(Timepre[v]);
}
int main() {
fill(dis, dis + 510, inf);
fill(Time, Time + 510, inf);
fill(weight, weight + 510, inf);
fill(e[0], e[0] + 510 * 510, inf);
fill(w[0], w[0] + 510 * 510, inf);
int n, m;
scanf("%d %d", &n, &m);
int a, b, flag, len, t;
for(int i = 0; i < m; i++) {
scanf("%d %d %d %d %d", &a, &b, &flag, &len, &t);
e[a][b] = len;
w[a][b] = t;
if(flag != 1) {
e[b][a] = len;
w[b][a] = t;
}
}
scanf("%d %d", &st, &fin);
dis[st] = 0;
for(int i = 0; i < n; i++)
dispre[i] = i;
for(int i = 0; i < n; i++) {
int u = -1, minn = inf;
for(int j = 0; j < n; j++) {
if(visit[j] == false && dis[j] < minn) {
u = j;
minn = dis[j];
}
}
if(u == -1) break;
visit[u] = true;
for(int v = 0; v < n; v++) {
if(visit[v] == false && e[u][v] != inf) {
if(e[u][v] + dis[u] < dis[v]) {
dis[v] = e[u][v] + dis[u];
dispre[v] = u;
weight[v] = weight[u] + w[u][v];
} else if(e[u][v] + dis[u] == dis[v] && weight[v] > weight[u] + w[u][v]) {
weight[v] = weight[u] + w[u][v];
dispre[v] = u;
}
}
}
}
dfsdispath(fin);
Time[st] = 0;
fill(visit, visit + 510, false);
for(int i = 0; i < n; i++) {
int u = -1, minn = inf;
for(int j = 0; j < n; j++) {
if(visit[j] == false && minn > Time[j]) {
u = j;
minn = Time[j];
}
}
if(u == -1) break;
visit[u] = true;
for(int v = 0; v < n; v++) {
if(visit[v] == false && w[u][v] != inf) {
if(w[u][v] + Time[u] < Time[v]) {
Time[v] = w[u][v] + Time[u];
Timepre[v]=u;
NodeNum[v]=NodeNum[u]+1;
} else if(w[u][v] + Time[u] == Time[v]&&NodeNum[u]+1<NodeNum[v]) {
Timepre[v]=(u);
NodeNum[v]=NodeNum[u]+1;
}
}
}
}
dfsTimepath(fin);
printf("Distance = %d", dis[fin]);
if(dispath == Timepath) {
printf("; Time = %d: ", Time[fin]);
} else {
printf(": ");
for(int i = dispath.size() - 1; i >= 0; i--) {
printf("%d", dispath[i]);
if(i != 0) printf(" -> ");
}
printf("\nTime = %d: ", Time[fin]);
}
for(int i = Timepath.size() - 1; i >= 0; i--) {
printf("%d", Timepath[i]);
if(i != 0) printf(" -> ");
}
return 0;
}`

**Comment by liuchuo** [comment]
谢谢小哥哥写的分析，小哥哥我发现你不会用代码块，不如我教你吧，嘿嘿～
如果是行内代码（inline）就直接一个撇就行啦，`return 0;`
如果是多行代码块，就在代码块的前一行和最后一行分别加三个撇，如下：
```
#include <iostream>
using namespace std;
int main() {
	return 0;
}
```
告诉你个小秘密哦，在这个文本框里面写的时候，上面有个preview按钮，按了之后就能看到自己写的最后发布后的效果了～摸摸头～

**Comment by liuchuo** [comment]
啊看了下，怪我第一次评论没讲清楚，我的意思是，想要一段对这道题目整个代码的题解分析给来看这道题目题解的人看～（你可以在我原分析的基础上稍作修改，因为我已经很久没有做pat题目了，怕写不出刚接触这道题时候的详细准确的题解分析，你刚刚对这道题做了完善应该比我熟悉很多），拜托啦～
以下是我原来代码的分析内容：
用两个Dijkstra + DFS。一个求最短路径（如果相同求时间最短的那条），一个求最快路径（如果相同求结点数最小的那条）~~~求最短路径可以直接在Dijkstra里面求前驱结点pre数组~~~求最快路径因为要求结点数最小的那条，所以要用pre的二维数组存储所有结点的最快路径，然后用DFS求出满足条件的结点数最小的那条~~~~

再次感谢～

**Comment by xminjie** [comment]
上面同学修改的代码写的很好，学到了
我按照学姐原来的思路，写了简短的分析，如果谁有更好的分析，欢迎替换掉我的～
分析
     1.用两个Dijkstra。一个求最短路径（如果相同求时间最短的那条），一个求最快路径（如果相同求结点数最小的那条）~~~
     2.求最短路径,和最快路径都可以在Dijkstra里面求前驱结点dispre和Timepre数组~~
     3.dispre数组更新的条件是路径更短，或者路径相等的同时时间更短。
     4.求最快路径时候要多维护一个NodeNum数组，记录在时间最短的情况下，到达此节点所需的节点数量。
       Time数组更新的条件是，时间更短，时间相同的时候，如果此节点能让到达此节点是数目也变小，则更新Timepre，和NodeNum数组
     5.最后根据dispre 和Timepre数组递归出两条路径，比较判断，输出最终答案～
注意：
    如果直接使用DFS的话，会导致最后一个测试用例“运行超时”~~~
