### ISSUE TITLE
AdvancedLevel_C++/1067. Sort with Swap(0,*) (25) 代码问题

### ISSUE THREAD

**Issue by jiangxiaohe** [liuchuo/PAT#75]
是不是发到这里更合适些？O^O

题目中有一句代码写的感觉不对，和题目的模拟过程是相反的：
```cpp
        cin >> a[i];
改为：
    {   cin >> t; a[t] = i; }
```
比如按照源代码，示例的变化过程为：
{4, 0, 2, 1, 3}
Swap(4, 3) => {3, 0, 2, 1, 4}
Swap(3, 1) => {1, 0, 2, 3, 4}
Swap(1, 0) => {0, 1, 2, 3, 4}
当然了，柳神这个做法也是完全可以保证答案一致的，也可以证明（当0不在0位置时，每次交换都是一个包含0的并查集恢复的过程，交换的次数为并查集中元素的数目，如果改为我pull的形式，则含义与题意相同，每次均是0与其他元素交换，而柳神之前的代码的含义是最后再与0交换，交换的顺序不同不影响交换的次数）
更为本质的做法其实就是计算并查集的数目了，然后不需要模拟交换过程，注意分初始化时0是否在原位置两种情况即可。

**Comment by jiangxiaohe** [comment]
@liuchuo

**Comment by liuchuo** [comment]
这个代码是前两天才更新的，是@xminjie 给我提交的pull request

**Comment by jiangxiaohe** [comment]
不客气，还是谢谢柳神，做出出来题目就来这里看看答案
