### ISSUE TITLE
1007.Maximum Subsequence Sum (25)题目反馈

### ISSUE THREAD

**Issue by CaiNiaoHui** [liuchuo/PAT#77]
题目中写到：
then its maximum sum is defined to be 0, and you are supposed to output the first and the last numbers of the whole sequence.
因此我认为当输入的值全部为负数时，应该输出first sequence 和last sequence,但是学姐你给的代码中忽视了这个问题，因此我认为需要增加几行代码
	
- firstsub=v[0];
- 	lastsub=v[k-1];
- 	if(sum<0)
- 	{
- 		sum = 0;
- 		v[leftsub]=firstsub;
- 		v[rightsub]=lastsub;
- 	} 
个人认为主要是记录第一个数和最后一个数。

有不对的地方希望学姐赐教！！！萌萌哒(^ω^)

**Comment by liuchuo** [comment]
我看了下我的代码貌似考虑到了呀，我们说的是同一段代码么？以下是我的代码：
```
#include <iostream>
#include <vector>
using namespace std;
int main() {
    int n;
    scanf("%d", &n);
    vector<int> v(n);
    int leftindex = 0, rightindex = n - 1, sum = -1, temp = 0, tempindex = 0;
    for (int i = 0; i < n; i++) {
        scanf("%d", &v[i]);
        temp = temp + v[i];
        if (temp < 0) {
            temp = 0;
            tempindex = i + 1;
        } else if (temp > sum) {
            sum = temp;
            leftindex = tempindex;
            rightindex = i;
        }
    }
    if (sum < 0) sum = 0;
    printf("%d %d %d", sum, v[leftindex], v[rightindex]);
    return 0;
}
```

**Comment by CaiNiaoHui** [comment]
是这段代码，不过，如果输入的全是负数，则输出的结果是0 0 0，这和题目的要求不符

**Comment by CaiNiaoHui** [comment]
1. # include<iostream>
2. # include <vector>
3. 
4. using namespace std;
5. 
6. int main()
7. {
8. 	int k;
9. 	scanf("%d",&k);
10. 	vector<int> v(k);
11. 	//tempsub 储存的临时起点 
12. 	int sum=-1,leftsub=0,rightsub=k-1,temp=0,tempsub=0;
13. 	int firstsub=0,lastsub=0;
14. 	
15. 	for(int i=0; i<k; i++)
16. 	{
17. 		scanf("%d",&v[i]);
18. 		firstsub=v[0];
19. 		lastsub=v[k-1];
20. 		
21. 		temp += v[i];
22. 		if(temp<0)
23. 		{
24. 			temp=0;
25. 			tempsub=i+1;
26. 		}
27. 		else if(temp>sum)
28. 		{
29. 			sum=temp;
30. 			leftsub = tempsub;
31. 			rightsub = i;
32. 		}
33. 		
34. 	}
35. 	if(sum<0)
36. 	{
37. 		sum = 0;
38. 		v[leftsub]=firstsub;
39. 		v[rightsub]=lastsub;
40. 	} 
41. 		
42. 	printf("%d %d %d",sum,v[leftsub],v[rightsub]);
43. 	
44. 	return 0;
45. } 

这是我的代码，在你的基础上添加了一下自己的想法

**Comment by CaiNiaoHui** [comment]
```
# include<iostream>
# include <vector>

using namespace std;

int main()
{
	int k;
	scanf("%d",&k);
	vector<int> v(k);
	int sum=-1,leftsub=0,rightsub=k-1,temp=0,tempsub=0;
	int firstsub=0,lastsub=0;
	
	for(int i=0; i<k; i++)
	{
		scanf("%d",&v[i]);
		firstsub=v[0];
		lastsub=v[k-1];
		
		temp += v[i];
		if(temp<0)
		{
			temp=0;
			tempsub=i+1;
		}
		else if(temp>sum)
		{
			sum=temp;
			leftsub = tempsub;
			rightsub = i;
		}
		
	}
	//全部为负数则更新sum值和起始下标终止下标 
	if(sum<0)
	{
		sum = 0;
		v[leftsub]=firstsub;
		v[rightsub]=lastsub;
	} 
		
	printf("%d %d %d",sum,v[leftsub],v[rightsub]);
	
	return 0;
} 
```

这是我的代码，在学姐你的基础上改进了一下

**Comment by liuchuo** [comment]
我刚试了一下，输入
```
3
-1 -2 -3
```
结果是
```
0 -1 -3
```
是这样的结果吗？

**Comment by liuchuo** [comment]
本身这段代码
```
int leftindex = 0, rightindex = n - 1;
……
 else if (temp > sum) {
            sum = temp;
            leftindex = tempindex;
            rightindex = i;
        }
```
应该就保证了temp > sum的时候leftindex和rightindex才会被改变，如果都是负数就不会改变这两个变量，最后输出的不就是v[leftindex], v[rightindex]第一个值和最后一个值了喵？我理解的不知道对不对

**Comment by CaiNiaoHui** [comment]
嗯，对，可能是我书写的代码的时候，思考错了，嗯，谢谢学姐的回答↖(^ω^)↗，我会努力向学姐学习。

**Comment by liuchuo** [comment]
嗯嗯那就好，我写代码时候比较懒，能少写点少写点，看到then its maximum sum is defined to be 0, and you are supposed to output the first and the last numbers of the whole sequence.直接就想到的是通过初始化保证最后没被更新的时候输出的是第一个和最后一个～
