### ISSUE TITLE
PAT-A-1149/B-1090的一些问题与建议

### ISSUE THREAD

**Issue by yinziminganion** [liuchuo/PAT#79]
~~1、题目叙述中告知N≤10^4，但实际数据应为≤10^5，如果未注意而采用了前者作为数组的大小（开大数组法）会造成段错误（这与题解没有关系，可能是题目录入错误，但这也许是学姐使用<map>的原因之一，关于<map>和<unordered_map>之后还有一些说明）；~~（一时脑抽搞错了，这个不用看了……）

2、在最后判断是否能装在一起时，如果不能装在一起则置flag = 1，但是循环并未结束，所以可以在外层for中，在内层for执行完以后如果flag == 1则break，避免循环占用时间导致在大量数据下超时（虽然gcc在-O2选项下可能会做出一定的优化，但如果在循环中有其他的不影响正常结果的语句，可能会使优化没有效果，尽管在此题的测试数据中未能体现）；

3、在 issue #66 中看到学姐关于map(unordered_map)和开大数组的问题。在某些竞赛中开大数组确实很少见，但PAT中大部分涉及“ID”的题目都是采用五位数字（少部分可能是少于10位的字符串，另当别论），之所以使用五位数字我的猜想是为了照顾一些乙级的考生（比如以C语言+了解少量C++为主），并且一般10^5大小的数组不会在编译和正常运行时报错（没有越界等情况下）。所以比较好的建议是，乙级题解尽量（当然也只是尽量啦，有些确实用纯C不太好写的~）多使用纯C，甲级题解可以多使用常用的STL容器，这样可以照顾到不同层次的考生；

4、对于map、unordered_map以及大数组的进一步讨论。大数组虽然看上去很突兀，但是通常都与题目中给出的范围相一致，基本不会产生有人不能理解为什么开大数组的情况。大数组有个优点就是内存的高效的随机存储性能，即不管访问其第几个值（当然，是在不越界等情况下），都有很快的速度。但是对于map来讲，虽然它有自排序的优点，但是仍然需要通过一定的时间（猜测应该会使用二分查找，没有具体查看STL实现）定位到需要访问的下标，对于unordered_map应该更明显（线性时间，猜测），再加上STL的实现中存在一定的额外开销，可能相对于某些完全可以使用大数组的场合所需时间更长。所以在PAT的五位数字“ID”的情况下还是使用大数组为宜。

**Comment by liuchuo** [comment]
您好，是这样的，pat系统迁移之前，我从来没有使用过unoredered_map，然而迁移系统之后，我将我所有的代码都提交到了新系统（即pintia，拼题A）上面，发现很多题目运行超时、内存超限，我对这些超时不能AC的代码进行了改动，也就是你看到的我好几个题目使用了unoredered_map，这也是我根据不能AC的情况现学的一种方法（其实我本身对这种改法是很排斥的，也是迫不得已，我觉得代码还是以让人容易理解的方式呈现更好）
关于乙级里面使用了C++的问题，在我刷乙级题目的时候，那时候大一我刚学完C语言还不知道C++，一直用纯C写，结果发现有的题目做不出来或者过于复杂，我在翻看别的博主的代码的时候发现了C++这个很好用的东西，也让我产生了学习C++的想法（其实我当时也不太乐意，后来学完才发现，嗯，真香……）所以我觉得这并不会产生多少的困扰，如果在刷乙级时候能够让一些人像我当年一样知道要去学一点C++、一点C++ STL库函数而不是刷完了乙级觉得C没问题到了甲级时候产生又要应对编程语言不熟练的问题、又要应对一些没有接触过的算法，让自己不知所措的情况，我觉得这是有好处的，也是为未来算法之路减少一些学习成本、增加一些学习信心～

**Comment by liuchuo** [comment]
关于提前剪枝的问题，因为本次更新题目我是甲级4道+乙级5道+发博客写分析给自己限时共3小时内完成的，所以呈现的是我本次“模拟考试”情况下写的能AC的代码的原始情况，如果考虑优化的话确实应该如你所说提前结束for循环，不过既然我当时就这么写的，所以就直接放上去也无大碍啦～嘻嘻多多包涵～

**Comment by liuchuo** [comment]
不过很感谢你的提议哦～祝学习进步～

**Comment by yinziminganion** [comment]
感谢您从百忙之中抽出时间回复我的issue

对于乙级考生学习C++的问题，很多人一开始都会觉得使用C语言来写某些问题的时候会很吃力，在题解中也会看到C++的用法，进而去了解一些C++的特性。然而我的本意是，对于乙级和甲级都有的题目来说，在乙级的题解中可以多用一些可以让初学者更能理解的方法、适当加入一些C++成分，在甲级中可以正常使用STL等C++特性，这样可以使先刷乙级题再刷甲级题的人，在学习过程中对C++的使用方法会更加了解，慢慢地也会完成从C到C++的转变。（这只是个人看法，当然每个人的学习曲线都不一样，对于这个问题我觉得您可以使用问卷等方式，对访问者的水平进行了解，进而找出折衷的解决方案。）

另外，对于今年秋季PAT考试，好像展现出了一个趋势，就是会对题库中既有的题目进行改编，比如我注意到A1149改编自A1121，A1150改编自A1122，A1151改编自T1022，（A1148暂时还没有发现emmmmmm），所以我想评论一下 #66 中您说过的一句话，20分的简单题虽然简单，但是能优化的地方还是尽量要做到优化，说不定下一次就会成为甲级那道30分的大题，所以平时多对自己的代码进行优化肯定是有帮助的，不亚于多刷另外几道题。

柳神不仅是写出答案，更是对代码进行可读性等优化，您为之付出了很多努力我们都有目共睹，希望我们的认真学习能一直成为您坚持更新的动力。

**Comment by yinziminganion** [comment]
哎呀一时脑抽又搞错了（我这个毛病真的需要好好改一改了/捂脸），A1148改编自T1022，A1151改编自A1143

**Comment by liuchuo** [comment]
特意去看了下issue66 原来你在说那个问题 我以为你在说我有很多道题用了undered_map没有必要的问题……是这样的 那段时间很多人给我提更高效解法 可能正好是很多人刷题高峰期 甚至出现了一道题被改过来又改回原样又改过去的情况 github、csdn、博客加上离线版生成的那块，四处都要更新，加上更新代码是简单的但是还要写与之相匹配的分析就很耗费精力了 后来决定只接收真正有意义的（不是刻意为之的、不是无关紧要的变动）

**Comment by liuchuo** [comment]
算了 越说心情越不好 不提了
