### ISSUE TITLE
1093 的更优解法 

### ISSUE THREAD

**Issue by idealhunting** [liuchuo/PAT#80]
#include <iostream>
#include <bits/stdc++.h>
/*
该解法来自网络，找不到在哪个博主上看见的了~...。
相比从前向后的思路，这个思路是从后开始记录PAT数量，
与你blog中的算法相比能够更优，少了一次遍历。
最后膜拜下刘神，可以加个好友认识下吗。最近刷题，发现自己实在太差劲了QAQ。耗时，效率还低到极点，希望得到刘神的引路
*/
using namespace std;

int main()
{
    int flag = 0;
    int i,cnt = 0;
    int t = 0,a_t = 0,pat = 0;

    char a[100001];
    cin>>a;
    int len = strlen(a);
    for(i = len-1; i >= 0; i--) 
    {
        if(a[i] == 'T')
            t++;
        if(a[i] == 'A')
        {
            a_t = (a_t + t) % 1000000007;
        }
        if(a[i] == 'P')
        {
            pat = (pat + a_t) % 1000000007;

        }
    }
    cout<<pat<<endl;
    return 0;
}

**Comment by liuchuo** [comment]
不改了不改了，改了还得重写分析，啦啦

**Comment by liuchuo** [comment]
万一放博客上被别人说抄袭就不好了QAQ

**Comment by liuchuo** [comment]
我的好友位已经满啦……ORZ

**Comment by idealhunting** [comment]
嗯嗯 合计着想找到博主 问问博主的，但找了会没找到，好友位满了QAQ~ 希望以后能通过邮件和你请教学习上的问题😅-------- 原始邮件 --------主题：Re: [liuchuo/PAT] 1093 的更优解法  (#80)发件人：柳婼 收件人：liuchuo/PAT 抄送：tangzhezhe ,Author 万一放博客上被别人说抄袭就不好了QAQ

**Comment by liuchuo** [comment]
略略略
