### ISSUE TITLE
[Advanced/C++/1005] bug report

### ISSUE THREAD

**Issue by ghostlo** [liuchuo/PAT#92]
#include <iostream>
using namespace std;
int main() {
    string a;
    cin >> a;
    int sum = 0;
    for (int i = 0; i < a.length(); i++)
        sum += (a[i] - '0');
    string s = to_string(sum);
    string arr[10] = {"zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"};
    cout << arr[s[0] - '0'];
    for (int i = 1; i < s.length(); i++)
        cout << " " << arr[s[1] - '0'];
    return 0;
}

cout << " " << arr[s[1] - '0'];应为cout << " " << arr[s[i] - '0'];

**Comment by liuchuo** [comment]
已活捉bug，感谢～
