### ISSUE TITLE
[Advanced/C++/1145] 查找耗时的问题

### ISSUE THREAD

**Issue by Luofan-KK** [liuchuo/PAT#93]
在判断从哈希表里查找元素i所用时间时，你写了这样的代码
`
scanf("%d", &a);

        for (int j = 0; j <= tsize; j++) {

            ans++;

            int pos = (a + j * j) % tsize;

            if (v[pos] == a || v[pos] == 0) break;

        }
`
其中你的循环是从0到tsize。但是j=0和j=tsize时，pos的值不应该一样吗？为什么在查找时需要查找这一步？（这也是我对题干很好奇的部分）
感谢

**Comment by YinyuBC** [comment]
这题有bug，题目说得是平方试探，而不是双向平方试探，那我觉得试探 ceil(tsize/2) 次就没必要再继续了，因为tsize若为素数，n^2 % tsize可能的取值恰好会有 ceil(tsize/2) 种，ceil是向上取整

**Comment by Luofan-KK** [comment]
> 这题有bug，题目说得是平方试探，而不是双向平方试探，那我觉得试探 ceil(tsize/2) 次就没必要再继续了，因为tsize若为素数，n^2 % tsize可能的取值恰好会有 ceil(tsize/2) 种，ceil是向上取整

感谢答复
